feature/WF-12 user 입니다!
wafflestudio18-5/team4-server pull request #11
Opened 2020-12-23 16:12 UTC by guzus

부족한 점 발견하면 업데이트하겠습니다!

2020-12-23 17:11 UTC, YeonghyeonKO approved these changes
잘 확인하셨을거라고 생각하고 빠른 머지하였습니다 ㅎㅎ
그리고 resolve conflicts 눌러주세요!

2020-12-23 17:11 UTC, YeonghyeonKO commented on wafflow/user/serializers.py
> +        )
사소한 newline

2020-12-23 17:11 UTC, YeonghyeonKO commented on wafflow/user/views.py
> +    # POST /user
사실 이런 주석은 불필요하다고 생각하여 명훈님이나 저는 따로 명시하지는 않았습니다!
그리고 적고 싶으시다면 뒤에 / 붙이는게 맞는거같아요!

2020-12-23 17:11 UTC, YeonghyeonKO commented on wafflow/user/views.py
> +
redundant newline

2020-12-24 03:34 UTC, eldpswp99 requested changes
전체적으로 수정되어야 할 부분이 많네요 테스트를 빡세게 작성해서 제가 발견 못한 부분도 마저 찾는 것이 필요해보입니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/models.py
> +    nickname = models.CharField(max_length=16, unique=True)
이거에 대한 migration도 추가해서 commit 해야 할 것 같아요

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        )
그런데 여기에 newline이 있다는 건 black이 적용이 안된건데..따옴표도 혼재해서 사용되고 있구요 
 black pre commit이 적용되었나요? 
https://bmh8993.github.io/Python/auto-formatting-pep8-with-black-plus-git-hooks/
관련 글입니다

--black 따로 커밋하셨군요 확인했습니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        )
https://wafflow.atlassian.net/wiki/spaces/sprint2/pages/63012870
AuthorSerializer가 구현이 안돼있는거 같아요 추가 부탁드립니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        if UserProfile.objects.filter(nickname=nickname).exists():
model에서 이미 validation체크를 해서 이 부분은 필요없지 않나요? 아니면 따로 추가한 이유가 있으신가요?

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        if User.objects.filter(username=username).exists():
django의 user는 기본적으로 unique로 알고 있는데, 이 부분은 필요없지 않나요?

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        picture = validated_data.pop('picture')
만약 picture가 ""로 들어오는게 아니라 아예 들어오지 않는 경우 validation error가 날 것같은데 확인 부탁드려도 될까요? 만약 맞다면 의도된 사항인가요?

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        user.password = password
이러면 raw password를 저장하게 될 거에요. 해싱한 비밀번호를 저장하는 식으로 수정 부탁드려요
이게 로그인이 안되는 원인이지 않나 싶네요
https://docs.djangoproject.com/en/3.1/topics/auth/default/

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +    def validate(self, data):
별도의 logic이 없다면 삭제해도 될 듯 합니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        return super(UserSerializer, self).update(user, validated_data)
위의 password수정 관련 logic을 수정하더라도, 아래서 update를 한 번 더 하는 과정에서 password가 validated_data에 그대로 있어서 또 raw password가 저장될 것 같네요

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +    reputation = serializers.CharField()
reputation은 IntegerField가 더 적절해 보여요

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/views.py
> +        else:
이러면 /user/:id 에서도 로그인을 요구하게 될 것 같아요
https://nrg1392.gitbook.io/wafflow/user-api/get-user/get-v1-user-user_id

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/views.py
> +        serializer.is_valid(raise_exception=True)
is_valid를 호출한 이유가 있나요? data를 줄 필요도 없어보입니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/views.py
> +            data["answer_count"] = user.user_answers.count()
user_answers는  rating을 저장하는 다대다 테이블이고, answer_count와는 관련이 없습니다 수정 부탁드려요 아예 UserProfileSerializer에서 SerializerMethodField를 이용해서 다 구해주는 것이 좋아 보입니다 + is_active확인 필요합니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/views.py
> +            data["bookmark_count"] = user.user_questions.filter(bookmark=True).count()
마찬가지로 UserProfileSerializer가 있으니 serializer에서 구해주는 것이 자연스러워 보이고, question의 is_active확인하는 과정 또한 필요해보입니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/views.py
> +        serializer.is_valid(raise_exception=True)
마찬가지로 is_valid가 실행될 이유가 없어보여요 data또한 들어갈 이유도 없구요

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        userprofile.save()
이러면 partial=True의 의미가 없지 않나요? nickname = "" or 주지 않으면 validated_error가 날 것 같은데

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/views.py
> +            user.is_active = False
save() 필요해보입니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/user/views.py
> +        serializer.update(user, serializer.validated_data)
update함수를 호출하는거보다 serializer.save()를 사용하는 것이 좀 더 적절해 보입니다

2020-12-24 03:34 UTC, eldpswp99 commented on wafflow/wafflow/urls.py
> +    path('', include('rate.urls')),
main과 충돌이 날 것 같은데 pull 후 다시 commit부탁드려요

2020-12-24 04:06 UTC, guzus commented on wafflow/user/serializers.py
> +        )
앗 깜빡했네요 AuthorSerializer 구현하겠습니다

2020-12-24 04:06 UTC, guzus commented on wafflow/user/views.py
> +    # POST /user
넵넵

2020-12-24 04:11 UTC, guzus commented on wafflow/user/serializers.py
> +        if UserProfile.objects.filter(nickname=nickname).exists():
아 그게 각각 에러메시지를 표시하려고 그렇게 짰습니다! "username/nickname/email already exists" 이런식으로 한번에 메시지를 표시하려면 위 코드는 필요 없습니다.

2020-12-24 04:11 UTC, guzus commented on wafflow/user/serializers.py
> +        if User.objects.filter(username=username).exists():
username은 unique이고, email은 unique가 아니라고 합니다!

2020-12-24 04:12 UTC, guzus commented on wafflow/user/serializers.py
> +        picture = validated_data.pop('picture')
의도하긴 했는데, 다시 생각해보니 아예 들어오지 않는 경우도 생각하면 좋을 것 같네요! 반영하겠습니다.

2020-12-24 04:14 UTC, guzus commented on wafflow/user/serializers.py
> +    reputation = serializers.CharField()
앗 그렇네요 반영하겠습니다

2020-12-24 04:22 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        if User.objects.filter(username=username).exists():
아 넵 username을 말한건데 잘못 썼네요 메세지를 위한 거라면 이렇게 하셔도 될 것 같습니다

2020-12-24 04:24 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        if UserProfile.objects.filter(nickname=nickname).exists():
아마 제가 알기로 모델에서 "usename":"alreay exists"이런식으로 주는거로 알고있느데 혹시 확인 가능할까요?

2020-12-24 05:58 UTC, YeonghyeonKO requested changes

2020-12-24 05:58 UTC, YeonghyeonKO commented on wafflow/user/models.py
> +    picture = models.CharField(max_length=200)
@guzus 아 추가적으로 reputation이랑 picture가 지금 required=True라서 회원가입 시에 문제가 생길 것 같습니다!

2020-12-24 06:28 UTC, YeonghyeonKO commented on wafflow/user/models.py
> +    picture = models.CharField(max_length=200)
실제로 user가 가입하는 과정에서 serializer에서 문제가 생기네요

2020-12-25 02:38 UTC, YeonghyeonKO commented on wafflow/user/serializers.py
> +        if User.objects.filter(username=username).exists():
맞아요 deserialize 할 때 400에러 보내주면서 message로 중복 메시지 보내주더라구요

2020-12-25 03:19 UTC, guzus commented on wafflow/user/models.py
> +    picture = models.CharField(max_length=200)
@YeonghyeonKO 혹시 힌트 주실수 있나요? blank=True, null=True 해봤는데도 계속 ```
"reputation": [
        "This field is required."
    ]
``` 가 뜨네요ㅠㅠ

2020-12-25 03:22 UTC, guzus commented on wafflow/user/serializers.py
> +        user.password = password
아 그렇네요 감사합니다!

2020-12-25 08:00 UTC, guzus commented on wafflow/user/serializers.py
> +        if UserProfile.objects.filter(nickname=nickname).exists():
@eldpswp99 테스트해봤는데 DETAIL:  Key (username)=(m) already exists. 이렇게 뜨고 500 error로 납니다!

2020-12-25 08:13 UTC, YeonghyeonKO commented on wafflow/user/serializers.py
> +        )
@guzus 그럼 AuthorSerializer 구현하신 PR이 merge 되면 나머지 dependency있던 PR 들도 수정 후 커밋하겠습니다.

2020-12-25 08:14 UTC, YeonghyeonKO commented on wafflow/user/models.py
> +    picture = models.CharField(max_length=200)
@guzus 혹시 이 문제 해결하셨나요? 슬랙에서 말씀하신 password 관련 문제였나요??

2020-12-25 08:25 UTC, guzus commented on wafflow/user/models.py
> +    picture = models.CharField(max_length=200)
@YeonghyeonKO 이거는 serializer 문제였습니다! userserializer로 가입시켜야되는데 userprofileserializer로 해서 그렇게 되었습니다!

2020-12-25 11:29 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        if UserProfile.objects.filter(nickname=nickname).exists():
500으로 나나요??

2020-12-25 12:14 UTC, eldpswp99 requested changes

2020-12-25 12:14 UTC, eldpswp99 commented on wafflow/user/models.py
> +    picture = models.CharField(max_length=200, null=True)
CharField에는 blank=True가 더 적절해 보입니다

2020-12-25 12:14 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +    nickname = serializers.CharField(required=False, allow_blank=True, write_only=True)
nickname은 필수로 있어야하지않나요? required의 기본값은 True여서 False만 입력하면 될 듯 한데 require이 False인 것들은 이유가 있을까요?

2020-12-25 12:14 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        if not nickname or nickname == "":
만약 이부분에서 Error을 내기 위함이라면 그냥 required로 해도 동일한 에러가 날꺼라는 생각이 들어요

2020-12-25 12:14 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +        user.set_password(password)
위에서 이미 make_password도 해싱을 했는데 이렇게 되면 hashing한 패스워드를 또 비밀번호로 설정하게 될 거 같아요

2020-12-25 12:14 UTC, eldpswp99 commented on wafflow/user/serializers.py
>          return super(UserSerializer, self).update(user, validated_data)
password를 pop을 하지 않고 여기서 다시 update를 하면 위에서 set_password한게 의미가 없어질듯해요

2020-12-25 12:14 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +            "reputation",
picture추가 필요합니다

2020-12-25 12:14 UTC, eldpswp99 commented on wafflow/user/views.py
> +        serializer.is_valid()
raise_exception=True 넣어주세요

2020-12-25 12:14 UTC, eldpswp99 commented on wafflow/wafflow/urls.py
> +    path("", include("user.urls")),
merge하셨나요? merge하셨다면 answer url도 있어야 할 듯한데..

2020-12-25 12:19 UTC, YeonghyeonKO approved these changes

2020-12-25 12:19 UTC, YeonghyeonKO commented on wafflow/user/views.py
> +        if user.is_active == True:
`== True:` 빼도 상관없긴 합니당

2020-12-25 12:19 UTC, YeonghyeonKO commented on wafflow/user/serializers.py
> +    username = serializers.CharField()
AuthorSerializer는 deserialize 목적이 없어서 딱히 이 줄이 필요한가 생각이 듭니다

2020-12-25 12:19 UTC, YeonghyeonKO commented
나머지는 명훈님이 봐주셔서 수정하시면 될 것 같습니다

2020-12-25 14:39 UTC, guzus commented on wafflow/user/serializers.py
> +    nickname = serializers.CharField(required=False, allow_blank=True, write_only=True)
네 그게 create랑 update할 때 둘다 이 serializer를 사용하는데 update을 할 때 nickname, picture이 안 넣어질 수도 있어서 그렇게 해놨습니다!

2020-12-25 14:40 UTC, guzus commented on wafflow/user/serializers.py
> +    nickname = serializers.CharField(required=False, allow_blank=True, write_only=True)
required=True 인거는 지울게요!

2020-12-25 14:59 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +    nickname = serializers.CharField(required=False, allow_blank=True, write_only=True)
partial=True로 두시면 require없어도 될꺼에요 update할때

2020-12-25 15:12 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +    nickname = serializers.CharField(required=False, allow_blank=True, write_only=True)
이부분 다시 반영해주실수있을까요?
@guzus

2020-12-25 15:24 UTC, eldpswp99 approved these changes
코드 깔끔하게 할 수 있는게 있긴 한데 그거 외에는 딱히 없어보입니다 고생 많으셨습니다

2020-12-25 15:24 UTC, eldpswp99 commented on wafflow/user/serializers.py
> +            picture = ""
None 대신에 "" 하시면 깔끔하게 한줄로 가능합니다

2020-12-25 15:27 UTC, guzus commented
모두들 정말 감사합니다ㅠㅠ 제가 django도 그렇고 github도 미숙해서 힘들게 한 것 같습니다..

2020-12-25 15:52 UTC, merged