WF-3 [back] Create Question App
wafflestudio18-5/team4-server pull request #12
Opened 2020-12-23 20:48 UTC by YeonghyeonKO

# Major Changes
[WF-3](https://trello.com/c/whTs6kGt)
## - Question App 생성
- serializer를 통한 Question create
- serializer를 최대한 세분화

<br>

** `GET /question/tagged/{tags}/` 및 `GET /question/search/keywords/`를 제외한 나머지 API는 구현된 상태임.

2020-12-24 08:03 UTC, YeonghyeonKO reviewed
@guzus @eldpswp99 
filter_by 기능 빼고는 다 완료한 상태고 black이나 오탈자는 곧 커밋하도록 하겠습니다

2020-12-24 08:03 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        questions = questions.order_by("-created_At")
created_at으로 수정하겠습니다

2020-12-24 11:17 UTC, eldpswp99 requested changes
변경할게 꽤 있어 보입니당 테스트까지 빡세게 작성해서 제가 못찾은 부분까지 찾아 수정해야할 것 같아요 고생 많으셨습니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +            # "reputation": user.profile.reputation,
reputation은 주석 처리한 이유를 알 수 있을까요?

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +        user = question.user
이러면 question의 저자가 본인의 글을 북마크했는지를 리턴하게 되지 않나요? context에서 user을 가져오는게 필요해 보여요

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +        user = question.user
마찬가지로..

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +    content = serializers.SerializerMethodField()
SerializerMethodField를 사용하신 이유를 알 수 있을까요? CharField로 충분해 보여서요

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +        return question.content[0:39]
39는 의도하신 숫자인가요? constant variable추가해서 작업하는 것도 좋아보입니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +        user = self.context["request"].user
앞에서 user을 이런식으로 뽑으면 좋을거같아요

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +        return QuestionTagSerializer(question.question_tags, many=True).data
QuestionTagSerializer는 Tag Model을 기반으로 하고있는데, question.question_tags는 QuestionTag instance를 주게 되지 않나요?

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +    name = serializers.SerializerMethodField()
여기도 SerializerMethodField를 사용하신 이유를 알 수 있을까요? id = serializers.IntegerField(read_only=True)로 하고 별도의 설정 없이도 가능해 보입니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +
title이나 content가 blank=True가 아니여서 title,content를 주지 않으면 패스가 되지만, 빈 스트링으로 주면 serializer에서 partial=True 를 통과해서  validation error가 발생할 거에요 확인 부탁드립니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +    def get_name(self, question_tags):
만약 SerializerMethodField를 사용하시고자 한다면, question_tags가 아닌 question_tag 단수로 하는게 더 자연스러울듯 합니다 serializer는 기본적으로 하나만 받으니까요 many=True여도 결국 하나씩 넣어서 list만드는 느낌이고..

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +        return Tag.objects.get(id=question_tags.tag_id).name
과제 4 피드백에서 나왔었는데, question_tag.tag.id로 얻는것이 더 좋다고 하시더라구요. 만약 이 함수를 사용하시게 되면 저리 가는게 더 좋아보입니다.

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/urls.py
> +# router.register("question/search/keywords", QuestionKeywordsViewSet, basename="question_keywords")
keyword는 작동이 잘 안되나요?

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +                {"error": "질문하려면 로그인이 필요합니다."}, status=status.HTTP_401_UNAUTHORIZED
이미 permission_class 가 있어서 이 부분은 동작하지 않을거 같아요

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +                    if not Tag.objects.filter(name=tag).exists():
tag, create = Tag.objects.get_or_create(name=tag)하면 깔끔

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +            user_profile.reputation += 40
https://nrg1392.gitbook.io/wafflow/user-api/get-user
question자체만으로는 reputation을 계산하지 않아서 이부분 수정 부탁드려요

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +class QuestionUserSerializer(serializers.ModelSerializer):
SimpleQuestionSerializer을 상속하는게 낫지 않나요?

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(self.get_serializer(question).data)
QuestionIdSerializer을 받아와야 할 거같아요
content가없네요 QuestionSerializer는

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +        question = self.get_object()
404에 대한 처리가 필요해 보입니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +                status=status.HTTP_401_UNAUTHORIZED,
이 경우에는 403을 주어야 합니다.
https://nrg1392.gitbook.io/wafflow/question-api/put-v1-question-question_id

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +                {"error": "제목과 본문은 필수적으로 입력해야 합니다."}, status=status.HTTP_400_BAD_REQUEST
update의 경우 title이나 content가 둘다 없거나 비어있어도 아무 변화 없이 200을 리턴하게 됩니다. 비어있는지 체크하는 것과 뒤의 partial=True와도 충돌하게 되구요
https://nrg1392.gitbook.io/wafflow/question-api/put-v1-question-question_id
https://wafflestudio1-l3f6523.slack.com/archives/C01ELEGPSBG/p1608296054038200

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +            serializer.is_valid(raise_exception=True)
위에서 말했던 serializer의빈 스트링이 아마도 is_valid는 통과하지만 save()에서 에러가 날꺼에요 이부분은 확실치 않지만 어느 쪽에서든 에러가 날꺼에요 아마도 확인 부탁드려요

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +            QuestionSerializer(question, context=self.get_serializer_context()).data
QuestionSerializer에서는 content가 없어서 수정이 필요해 보입니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +        tags = tags.split(" ") if tags else None
tag들은 +로 나누지 않나요?

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +    @action(detail=False, methods=["GET"])
keyword를 위한 ViewSet을 하나 더 만드신 후에 `router.register("question/search/keywords",QuestoinKeywordsViewSet,basename="question_keywords")`
로 하고, list로 받으면 될꺼에요 제가 retrieve라 했었는데 keywords에서 keyword를 path params라고 잘못 생각했네요

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +        questions = Question.objects.filter(is_active=True, id__in=questions_id).all()
저도 이거랑 관련된 코드를 짜면서 고민했던 부분이긴한데, 이렇게 되면 결국 모든 question에 대해서 순회하게 되어서 pagination의 의미가 없지 않나 하는 생각이 들어요 저는 그래서
`questions_all = Question.objects.filter(
            is_active=True,
            user_questions__in=self.sorted_by_queryset(user_questions_all, sorted_by),
        )`

이런 식으로 최대한 queryset으로 남겨두려고 헀었거든요 이거는 구현 후에 debug toolbar에서 직접 하면서 차이를 느껴봐야 알 것 같습니다.

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +                {"error": "Invalid sorted_by."}, status=status.HTTP_404_NOT_FOUND
400리턴해주셔야합니다 https://app.gitbook.com/@nrg1392/s/wafflow/question-api/get-question/get-v1-question-tagged-tags

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +        questions = Question.objects.filter(is_active=True, id__in=questions_id).all()
Tag가 None or blank일 때 전체를 리턴해 주어야하는데 이부분 구현이 안돼있는거 같습니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +        keywords = keywords.split(" ") if keywords else None
마찬가지로 keyword도 +로 나누게 됩니다 https://app.gitbook.com/@nrg1392/s/wafflow/question-api/get-question/get-question-search-keywords & keyword none or blank일때 전체 question리턴해주어야되는데 이부분 구현되어있지 않은듯 합니다.

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +                {"error": "Invalid sorted_by."}, status=status.HTTP_404_NOT_FOUND
400 입니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +            return Response(
400입니다

2020-12-24 11:17 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(self.get_serializer(paginated_questions, many=True).data)
QuestionUserSerializer에는 tags, comment_count를 리턴하는데 원하는 body에서는 그게 없어서 수정이 필요해 보입니다

2020-12-24 16:49 UTC, YeonghyeonKO commented
![](https://github.trello.services/images/mini-trello-icon.png) [WF-3 [back] Question 생성, 수정, 조회 API](https://trello.com/c/whTs6kGt/28-wf-3-back-question-%EC%83%9D%EC%84%B1-%EC%88%98%EC%A0%95-%EC%A1%B0%ED%9A%8C-api)

2020-12-25 06:07 UTC, YeonghyeonKO reviewed
@eldpswp99 새벽에 달린거라 코드 퀄리티가... 흑흑 리뷰 감사합니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +            # "reputation": user.profile.reputation,
아 이 부분은 제가 @guzus 명구님 코드 넣고 포스트맨 돌렸을 때 user_profile 관련 오류가 떠서 추후에 **SimpleUserSerializer** (혹은 **AuthorSerializer)로** 변경할 예정입니다!

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +            # "reputation": user.profile.reputation,
근데 어차피 테스트 짜야하니깐 주석 해제하는게 낫겠네요

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +        user = question.user
윽 마지막에 검토하다가 헷갈려서 context user에서 question.user로 바꿨나봅니다 수정할게요!

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +        return question.content[0:39]
앗 네 api docs에 Tag와 Search일 때는 처음 40자만 보여준다고 해서 의도한 바가 맞습니다. 숫자는 하드코딩 대신 constant에서 관리하는게 낫겠네요 ㅎㅎ
` "content": Question content - first 40 texts of content,`

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +        return question.content[0:39]
```python
CONTENT_FOR_TAG_SEARCH = 40
```
으로 정의 후 
```python
def get_content(self, question):
    return question.content[0:CONTENT_FOR_TAG_SEARCH]
```
로 수정했습니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +
```python
        if title != "" and content != "":
            serializer = self.get_serializer(question, data=data, partial=True)
            serializer.is_valid(raise_exception=True)
            serializer.save()
        return Response(
            QuestionSerializer(question, context=self.get_serializer_context()).data
        )
```

이런 식으로 title (or content) 또는 둘 다 비어있다면 수정하지 않는걸로 가겠습니당

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +    def get_name(self, question_tags):
그렇네요 단수형이 더 자연스러운 것 같습니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            user_profile.reputation += 40
아 넵 제가 이 부분은 착각했네요!

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +    @action(detail=False, methods=["GET"])
넵 ViewSet 새로 파서 list로 하겠습니당_

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/urls.py
> +# router.register("question/search/keywords", QuestionKeywordsViewSet, basename="question_keywords")
수정하였습니다

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +                    if not Tag.objects.filter(name=tag).exists():
으 get_or_create 알고 있었는데도 실생활에 적용을 안했다니..

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(self.get_serializer(question).data)
retrieve 용으로 만든 serializer였는데 다른걸 썼네요 ㅠ

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        question = self.get_object()
수정했습니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +                status=status.HTTP_401_UNAUTHORIZED,
수정했습니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            QuestionSerializer(question, context=self.get_serializer_context()).data
수정했습니다

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        tags = tags.split(" ") if tags else None
아 이 부분 관련해서는 POST에서의 tag와는 다르게 query_params라는 점이 다릅니다.
이때 `tags = request.query_params.get("tags")`로 가져오면 알아서 +가 사라지고 공백으로 구분되는 string 형태가 되더라구요

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            QuestionSerializer(question, context=self.get_serializer_context()).data
그리고 Answer App과의 통일성을 위해 QuestionIdSerializer -> QuestionInfoSerializer로 개명했습니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        questions = Question.objects.filter(is_active=True, id__in=questions_id).all()
이 부분 짜면서 현타오긴 했는데.. ㅋㅋㅋㅋㅋ 이건 더 공부하고 toolbar 참고하면서 DB 최대한 덜 때리게 수정하겠습니다!

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +                {"error": "Invalid sorted_by."}, status=status.HTTP_404_NOT_FOUND
수정했습니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        keywords = keywords.split(" ") if keywords else None
넵 수정했습니다. (keyword + 부분은 tag 때와 마찬가지로 query_params로 get할 때 띄어쓰기로 변환됩니다)

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +                {"error": "Invalid sorted_by."}, status=status.HTTP_404_NOT_FOUND
수정했습니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        questions = Question.objects.filter(is_active=True, id__in=questions_id).all()
이건 문서에 따로 없지만 404가 아직 안쓰였기 때문에 `{"error": "Please enter tags"}, status=status.HTTP_404_NOT_FOUND` 로 하겠습니다!

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            return Response(
수정했습니다.

2020-12-25 06:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(self.get_serializer(paginated_questions, many=True).data)
넵 QuestionUserSerializer에 tags, comment_count 빼고 QuestionSerializer에 추가했습니다.

2020-12-25 06:36 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +
이게 partial=True를 적용시키기 위해서 이러면 또 title은 주고 content를 빈 스트링으로 주면 validation error가 날 꺼에요
만약 ""라면 None으로 줘서 그냥 serializer에서 무시하도록 하는게 좋아보여요

2020-12-25 06:39 UTC, eldpswp99 commented on wafflow/question/views.py
> +        tags = tags.split(" ") if tags else None
ㅇㅎ 그렇군요

2020-12-25 06:39 UTC, eldpswp99 commented on wafflow/question/views.py
> +        questions = Question.objects.filter(is_active=True, id__in=questions_id).all()
넹넹

2020-12-25 06:40 UTC, eldpswp99 commented on wafflow/question/views.py
> +        questions = Question.objects.filter(is_active=True, id__in=questions_id).all()
이거 API문서에 기록되어있습니다

2020-12-25 06:40 UTC, eldpswp99 commented on wafflow/question/views.py
> +        questions = Question.objects.filter(is_active=True, id__in=questions_id).all()
https://app.gitbook.com/@nrg1392/s/wafflow/question-api/get-question/get-v1-question-tagged-tags

2020-12-25 08:18 UTC, eldpswp99 requested changes
몇 부분만 더 수정하면 괜찮아 보입니다 화이팅!

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +    def get_name(self, question_tag):
이 부분도 charField로 가능해 보여요

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/urls.py
> +router.register(
굳 작동  되나요?

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/views.py
> +        if title != "" and content != "":
이 부분이 title이나 content에 빈 스트링이 오면 그 부분은 무시하고 update가 진행되어야 합니다. 둘다 blank or None이면 그냥 아무것도 안바꾸고 둘 중 하나만 blank or None이면 내용이 있는 것만 바꿉니다. 그 부분을 적용시켜서 바꿔주실수 있을까요? title = title if title != "" else None & content = content if content != "" else None 이정도로 구현은 가능해 보입니다 이쁘진 않지만 구현만이라면.. 지금 내용은 partial update를 적용시키지 못하고 있습니다

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/views.py
> +            return Response(
keyword가 없으면 default로 all question을 리턴하게 됩니다. https://nrg1392.gitbook.io/wafflow/question-api/get-question/get-question-search-keywords blank면 빈 리스트..? 아니면 all? 이건 좀 더 생각해봐야겠네요

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/views.py
> +        if not tags:
마찬가지로 tag None이면 전체 리턴하게 됩니다 blank나 맞는 question없는 경우는 빈 리스트로 리턴하게 됩니다
https://app.gitbook.com/@nrg1392/s/wafflow/question-api/get-question/get-v1-question-tagged-tags/@drafts

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +        model = Tag
Model을 questionTag로 바꾸는 것이 더 적절해 보입니다

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +    id = serializers.IntegerField(source="question_tag.tag.id", read_only=True)
모델을 questionTag로 바꾸고, source="tag.id"로 하면 동작할꺼에요 지금 이 코드는 동작할지 확신이 없네요

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/views.py
> +        try:
is_active = False면 400리턴하는 로직을 여기도 추가하는게 좋을거 같아요

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/views.py
> +            QuestionSerializer(question, context=self.get_serializer_context()).data,
QuestionInfoSerializer을 사용해야할거같습니다

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/views.py
> +        question.view_count += 1
사실 이 viewCount는 캐시를 사용해서 같은 유저가 30분 이내에 또 접속하면 카운트하고 싶지 않긴 한데.. 이건 나중에 redis추가해서 추가하면 좋을거 같네요 지금은 새로고침 꾹누르면 막올라가서

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/views.py
> +        user = request.user
여기도 is_active로직 추가해야할듯해요

2020-12-25 08:18 UTC, eldpswp99 commented on wafflow/question/views.py
> +            user = User.objects.get(pk=pk)
is_active로직 추가 필요해보입니다

2020-12-25 08:40 UTC, eldpswp99 requested changes
is_active 관련 로직 필요해보입니다

2020-12-25 08:40 UTC, eldpswp99 commented on wafflow/question/views.py
> +            question = Question.objects.get(pk=pk)
is_active 추가 필요해보입니다

2020-12-25 08:40 UTC, eldpswp99 commented on wafflow/question/views.py
> +            question = Question.objects.get(pk=pk)
여기도 is_active

2020-12-25 08:40 UTC, eldpswp99 commented on wafflow/question/views.py
> +        questions = Question.objects.filter(
is_active 추가 필요해보입니다

2020-12-25 08:40 UTC, eldpswp99 commented on wafflow/question/views.py
> +            user = User.objects.get(pk=pk)
is_active추가 필요합니다 다른 곳에서 제가 발견 못했을수도 있어서 전체적으로 is_active에 대해서 한번 확인해주세요

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +    id = serializers.IntegerField(source="question_tag.tag.id", read_only=True)
아 제가 name만 제대로 보내고 있었네요 수정했습니다!

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/urls.py
> +router.register(
넵 작동됩니다!

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            QuestionSerializer(question, context=self.get_serializer_context()).data,
수정했습니다

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            question = Question.objects.get(pk=pk)
수정했습니다

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        question.view_count += 1
맞아요 저도 인지하고 있어서 (약간 2000년대 웹페이지 조회수 늘리는 거 생각나네요) 추후에 redis로 해보겠습니다

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        user = request.user
@eldpswp99  user는 request에서 받아오는거라 is_active 추가안해도 상관없지 않나요?

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            question = Question.objects.get(pk=pk)
수정했습니다

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        questions = Question.objects.filter(
수정했습니다.

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            user = User.objects.get(pk=pk)
넵!!

2020-12-25 15:14 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        if title != "" and content != "":
```python
        data = request.data.copy()
        title = data.get("title")
        content = data.get("content")

        if not title:
            data["title"] = question.title
        if not content:
            data["content"] = question.content

        serializer = self.get_serializer(question, data=data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(
            QuestionInfoSerializer(question, context=self.get_serializer_context()).data
        )
```

이런 식으로 수정해보았습니다. " "로 받으면 blank Error가 뜨는건 의도한거지요?

2020-12-25 15:18 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +            return Response(
이 부분은 곧 커밋하겠습니다

2020-12-25 15:18 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        if not tags:
이 부분은 곧 커밋하겠습니다

2020-12-25 15:35 UTC, eldpswp99 requested changes

2020-12-25 15:35 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +            user = request.user
음.. 전체적으로 로직이 이렇게 바뀐거 같은데 이렇게 로직을 바꾼이유가 있을까요?

2020-12-25 15:35 UTC, eldpswp99 commented on wafflow/question/views.py
> +        question = Question.objects.filter(pk=pk, is_active=True).last()
get을 써도 되지 않나요? 로직을 바꾼 이유가 있을까요?

2020-12-25 15:35 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(
이 부분 get_serializer로 안하신 이유가 있나요?

2020-12-25 15:35 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(
get_serializer이용 안한이유가 있을까요?

2020-12-25 15:35 UTC, eldpswp99 commented on wafflow/question/views.py
>              return None
404 response를 return 하는게 필요해보입니다

2020-12-25 15:45 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +            user = request.user
아 이 부분이 Anonymous일 때 context를 제대로 받아들이지 못해 500 error가 뜨는 것 같더라구요.. 구글링하니깐 안전하게 이 방식을 추천하기도 했고 실제로 postman으로 날려보니깐 이 방식으로는 동작해서 바꾸었습니다.

2020-12-25 15:47 UTC, eldpswp99 commented on wafflow/question/views.py
> +        user = request.user
맞네요

2020-12-25 15:48 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +            user = request.user
넵 좋네요!

2020-12-25 15:48 UTC, eldpswp99 commented on wafflow/question/views.py
> +        if title != "" and content != "":
""라면 무시하겠지만 " "로 받으면 수정이 되어야 할텐데.. 에러가 뜨나요?

2020-12-25 15:53 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        question = Question.objects.filter(pk=pk, is_active=True).last()
아 사실 상관없는데 is_active까지 한꺼번에 처리하려고 했습니다!

2020-12-25 15:53 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(
이 부분 위의 get_serializer_class에서 정의한대로 **QuestionTagSearchSerializer**로 돌아가는게 맞는데 (실제로 `print(self.get_serializer())` 해도 **QuestionTagSearchSerializer** 함수 출력됨) get_serializer로 하니깐 희한하게 url이 꼬이는지 500 error가 뜨더라구요

2020-12-25 15:53 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(
위랑 마찬가지 이유였습니다!

2020-12-25 15:53 UTC, YeonghyeonKO commented on wafflow/question/views.py
>              return None
수정했습니다.

2020-12-25 15:55 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(
context 같이 주는건 어떤가요? 만약을 위해..?

2020-12-25 15:55 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        if title != "" and content != "":
네 Validation Error 뜨긴 하는데 Django에서 의도한 기능이라고 생각하긴 했는데 명훈님은 아예 " "이 저장되는 걸 의도하신건가요?

2020-12-25 15:56 UTC, eldpswp99 commented on wafflow/question/views.py
> +        question = Question.objects.filter(pk=pk, is_active=True).last()
음.. question = Question.objects.get(pk=pk,is_active=True)하고 try_except하면 되지 않나요?

2020-12-25 15:56 UTC, YeonghyeonKO commented on wafflow/question/serializers.py
> +            user = request.user
흠 그래서 저는 오히려 명훈님이 context에서 user꺼내오는 과정이 왜 오류가 안나는지 궁금하네요 ㅋㅋㅋ

2020-12-25 15:57 UTC, eldpswp99 commented on wafflow/question/serializers.py
> +            user = request.user
테스트 환경에서 그래서 그런거일수도 있다는 생각이 드네요.. 일단 저도 엑조디아 합치고 구동시키면서 버그를 잡아야할거 같습니다

2020-12-25 15:57 UTC, eldpswp99 commented on wafflow/question/views.py
> +        if title != "" and content != "":
그렇긴 했는데 사실 저거 validation error가 뜬다면 그것도 맞을거 같네요 굳이 안건드리셔도 될듯 합니다

2020-12-25 16:07 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        question = Question.objects.filter(pk=pk, is_active=True).last()
@eldpswp99 억 단일 column에 대해서만 get할 수 있는 줄 알았는데 아니네요
흠 관련 filter 함수 다 수정하겠습니다

2020-12-25 16:08 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(
넵! 혹시 염두에 두신 만약이 어떤 케이스인가요?

2020-12-25 16:09 UTC, eldpswp99 commented on wafflow/question/views.py
> +        if title != "" and content != "":
아 잠시만요 이거 validation Error가 뜨면 안되는데..

2020-12-25 16:09 UTC, eldpswp99 commented on wafflow/question/views.py
> +        if title != "" and content != "":
제가 헷갈렸네요 이게 원래는 그냥 스트링이 비지 않으면 그냥 덮어쓰고 만약 빈 스트링이라면 무시하는게 필요한데 왜 valdiaton이 뜨는거지..

2020-12-25 16:10 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(
저기 위의 context에서 user을 받아오는 경우에서 context를 전달하지 않아 문제가 생길 수 있다는 생각이 들어서요

2020-12-25 16:10 UTC, eldpswp99 commented on wafflow/question/views.py
> +        if title != "" and content != "":
@YeonghyeonKO

2020-12-25 16:11 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        if title != "" and content != "":
빈 스트링("")이 아니라 " "라서 무시는 안되는거 아닌가요?
(빈 스트링에서는 무시되는거 확인했습니다.)

2020-12-25 16:16 UTC, eldpswp99 commented on wafflow/question/views.py
> +        if title != "" and content != "":
@YeonghyeonKO 음 약간 잘못된 걸로 수정하는 그런 느낌인가 보네요 넵 그대로 둬도 괜찮을듯 합니다

2020-12-25 16:18 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(
아 이에 대해서 지금과 같이 Anonymousdls 경우에 context 넘겨주면 
```python
return Response(
    QuestionTagSearchSerializer(paginated_questions, many=True, context=self.get_serializer_context()).data
)
```
`TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x106ba8160>.`

이렇게 에러가 뜨더라구요. 아마 get_serializer에서 500 error 떴던 이유도 error 메시지가 같은 걸 보아하니 context를 넘겨주는 과정에서 문제가 생기는 것 같습니다.

2020-12-25 16:21 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(
@YeonghyeonKO  오..신기하네요 일단 이렇게 가야겠네요

2020-12-25 16:23 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(
그런데 이러면 context를 못받을거 같은데 괜찮나요? 지금 context를 사용하는 부분이 없어서 괜찮은가요

2020-12-25 16:25 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(
현재 serializer에서는 괜찮은 거 같아요

2020-12-25 16:26 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(
@YeonghyeonKO 지금 확인했는데 이거 TagSerializer 가 QuestionSerializer을 상속하면서 rating을 받게 되는데 이 부분이 문제가 되지 않나요?

2020-12-25 16:30 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        question = Question.objects.filter(pk=pk, is_active=True).last()
Comment App에 대해서도 수정하겠습니다.

2020-12-25 16:44 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(
@eldpswp99 네네 만약에 
```python
user = self.context["request"].user
if isinstance(user, AnonymousUser):
    return 0
```
이렇게 고쳐서 postman으로 GET API 날려보면 아래와 같이 뜹니다.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/46114393/103139045-9d14b080-471b-11eb-920c-eaa2fdf64315.png">


이 에러 피하려고 
```python
user = None
request = self.context.get("request")
if request and hasattr(request, "user"):
    user = request.user
```
를 사용했더니 동작했습니다.

2020-12-25 16:48 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return Response(
@YeonghyeonKO 아뇨 Tag search 해서 Get 받는 api에서 response body 에는 rating이 없어서요 근데 상속해주는 serializer에서는 rating이 있어서 body에 추가될 거 같아요

2020-12-25 18:18 UTC, YeonghyeonKO commented on wafflow/question/views.py
> +        return Response(
@eldpswp99 
명훈님 뒤늦게 questions : []로 감싸주는 serializer 추가했더니 self.get_serializer()도 잘 동작하고 context도 serializer 안에 잘 들어가네요 ㅋㅋㅋ...

2020-12-25 18:24 UTC, merged