WF-25 [back] resolve Answer page null problem
wafflestudio18-5/team4-server pull request #17
Opened 2020-12-26 15:00 UTC by eldpswp99

answer의 page가 null일 때 500에러를 뱉는것을 수정하였습니다

2020-12-26 15:52 UTC, YeonghyeonKO approved these changes
page 0 -1 다 확인했었는데 None일 때를 고려하지 않았었네요

2020-12-27 12:51 UTC, guzus requested changes

2020-12-27 12:51 UTC, guzus commented on wafflow/question/views.py
> +        return None
page = int(page) 빼먹으신게 아닌가 생각이 듭니다!

2020-12-27 12:51 UTC, guzus commented on wafflow/user/serializers.py
> +            user_profile.nickname = nickname
python case 규칙을 적용하셨군요! 감사합니다

2020-12-27 12:55 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return None
내부적으로 int(page)를 적용하더라구요

2020-12-27 12:56 UTC, eldpswp99 commented on wafflow/question/views.py
> +        return None
answer test로 int없이 돌아가는것을 확인하였습니다

2020-12-27 12:56 UTC, guzus commented on wafflow/question/views.py
> +        return None
오 그렇군요!

2020-12-27 12:58 UTC, guzus approved these changes

2020-12-27 13:10 UTC, YeonghyeonKO approved these changes
LGTM

2020-12-27 14:42 UTC, merged