Initialize Django
wafflestudio18-5/team4-server pull request #2
Opened 2020-12-11 09:54 UTC by eldpswp99

장고 초기세팅/ pull request CI 세팅
앱 구조 구현
model 구현

2020-12-13 11:33 UTC, YeonghyeonKO requested changes
아직 모델 단계라서 수정해야 할 부분은 newline 정도밖에 없는 것 같은데
코멘트 남긴 것들에 대해 @guzus @eldpswp99 얘기해봤으면 하네요!

모델 짜느라 정말 수고하셨습니다... 아 혹시 postgresql 사용하면서 mysql과 다른 점 등의 후기를 남겨주실 수 있나요?

2020-12-13 11:33 UTC, YeonghyeonKO commented on .github/workflows/django.yml
> +      postgres:
웅장해지는군요

2020-12-13 11:33 UTC, YeonghyeonKO commented on .github/workflows/django.yml
> +          DEBUG=TRUE python manage.py test
yaml 파일도 다른 프로그래밍 언어와 마찬가지로 마지막 blank line을 권장하는 것 같네요

2020-12-13 11:33 UTC, YeonghyeonKO commented on .gitignore
> +.idea/
항상 파일 마지막 줄은 newline을 하시면 됩니다!

2020-12-13 11:33 UTC, YeonghyeonKO commented on wafflow/answer/models.py
> +    user = models.ForeignKey(User, related_name="answers", on_delete=models.CASCADE)
사실 question, user가 지워지지 않는 것으로 논의했기 때문에 answer 역시 db 상에서 제거되는 경우는 없지만 ForeignKey에서의 참조무결성 때문에 on_delete를 설정하신거죠?

2020-12-13 11:33 UTC, YeonghyeonKO commented on wafflow/answer/tests.py
> +from django.test import TestCase
과연 sprint 내에 TestCase를 작성할 수 있을 것인지...
사실 backend는 마음만 먹으면 가능할 것 같긴 해요 (각자 맡은 부분에 대해서 test 짠다음에 세 명이서 돌려가면서 추가하기)

2020-12-13 11:33 UTC, YeonghyeonKO commented on wafflow/comment/models.py
> +    content = models.CharField(max_length=500)
Answer에서처럼 5000으로 두지 않은 이유는 Question, Answer에 딸린 comment가 불필요하게 길어지면 페이지 운용에 있어 UI가 너무 지저분해지니깐 그런걸로 이해하면 될까요?

2020-12-13 11:33 UTC, YeonghyeonKO commented on wafflow/question/models.py
> +    has_accepted = models.BooleanField(default=False)
생각해보니 has가 아니라 is가 Question 입장에서 더 자연스러운 것 같긴 한데 (+ is_active, is_hidden과의 문법적 호응 역시) User가 accepted 했다고 본다면 has_accepted도 되긴 하네요 
처음 모델짤 때 명칭으로 뒤에 migration 생기면 좋지 않으니깐 지금 어떻게 할지 명구님이랑도 얘기해봐야겠습니다. 
@guzus 의견 부탁드립니다!

2020-12-13 11:34 UTC, YeonghyeonKO commented
아 그리고 PR 제목은 "Initialize Django" -> "WF-1 [back] Initialize Django and construct Models" 와 같이 통일하도록 합시다!

2020-12-13 11:35 UTC, eldpswp99 commented on wafflow/answer/models.py
> +    user = models.ForeignKey(User, related_name="answers", on_delete=models.CASCADE)
> 아 그리고 PR 제목은 [trello](https://trello.com/b/1DOat7lV/wafflow-kanban)에 카드를 남긴 것과 같이
> `Initialize Django` -> `WF-1 [back] Initialize Django and construct Models` 로 통일하도록 합시다!

앗.. 다른팀 참고해서 했는데 이게 낫겠네요 수정하겠습니다 :)

2020-12-13 11:36 UTC, eldpswp99 commented
> 아 그리고 PR 제목은 [trello](https://trello.com/b/1DOat7lV/wafflow-kanban)에 카드를 남긴 것과 같이
> `Initialize Django` -> `WF-1 [back] Initialize Django and construct Models` 등으로 통일하도록 합시다!
> 
> 아 그리고 PR 제목 영어로 하는거 좋아하는 편인데 가독성을 위해 길게 적으면 좋을 것 같습니다!

다른 팀 참고해서 했는데 이게 확실히 낫겠네요 수정하도록 하겠습니다 :)

2020-12-13 11:44 UTC, eldpswp99 commented
> 아직 모델 단계라서 수정해야 할 부분은 newline 정도밖에 없는 것 같은데
> 코멘트 남긴 것들에 대해 @guzus @eldpswp99 얘기해봤으면 하네요!
> 
> 모델 짜느라 정말 수고하셨습니다... 아 혹시 postgresql 사용하면서 mysql과 다른 점 등의 후기를 남겨주실 수 있나요?

사실 장고 선에서는 orm을 통해 동작하다보니 postgresql이라고 해서 특별한 것은 딱히 없었고, 있다면 settings 설정과, mysqlclient가 아닌 psycopg2를 사용하는 것 이상으로 크게 다른 점은 없었습니다.

다만 postgresql을 콘솔에서 사용할 때, postgres유저로 이동해서 psql을 통해 접속해서 조작할 수 있고, 세미콜론이 없으면 아예 그 문장이 실행이 되지 않고, 유저 등록에서도 유저를 추가하면 동명의 우분투 유저가 있어야 한다고 하는등(사실 이 부분은 그냥 따라하긴 했는데 잘 모르겠습니다) 자잘한 문법 차이를 제외하고도 약간 차이가 있더라구요. CI에서도 mysql할 때는 유저에 대한 privilege를 설정해 주어야하는데 postgresql은 따로 설정해 주지 않고, 유저네임을 postgres로 해도 CI가 동작하구요.

2020-12-13 11:45 UTC, eldpswp99 commented on .github/workflows/django.yml
> +          DEBUG=TRUE python manage.py test
이부분 전체 파일에 대해 수정해서 다시 커밋하도록 하겠습니다!
마지막 blank line은 대부분의 파일에 적용되는 convention인가요?

2020-12-13 11:46 UTC, eldpswp99 commented on wafflow/answer/models.py
> +    user = models.ForeignKey(User, related_name="answers", on_delete=models.CASCADE)
넵 만약 question, user을 db상에서 지우게 된다는 것은 저희가 생각했던 지우는 방식이 아니라(is_active를 이용한) 약간 강제적으로 지운다고 생각해서 참조무결성을 적용시키는게 낫다고 생각했습니다

2020-12-13 11:47 UTC, eldpswp99 commented on wafflow/answer/tests.py
> +from django.test import TestCase
넹넹 최대한 해보는게 좋을거같아요 테스트케이스의 중요성을 세미나때 많이 느꼈어서..

2020-12-13 11:48 UTC, eldpswp99 commented on wafflow/comment/models.py
> +    content = models.CharField(max_length=500)
네  stackoverflow에서 5줄 이상 넘어가는 comment는 좀 지저분해 보였고, stackoverflow에서 한 줄이 대략 100자정도 해서 500으로 해놓았습니다.

2020-12-13 11:50 UTC, eldpswp99 commented on .github/workflows/django.yml
> +      postgres:
:) 테스트까지 완료하길 바라면서..

2020-12-13 11:57 UTC, eldpswp99 commented on wafflow/question/models.py
> +    has_accepted = models.BooleanField(default=False)
answer는 accepted '된' 것이고, question은 accepted를 '하는' 입장이라고 생각해서 naming을 적용했습니다. 
+is_hidden에 대해서 설명을 부탁드려도 될까요?

2020-12-13 15:08 UTC, YeonghyeonKO commented on .github/workflows/django.yml
> +          DEBUG=TRUE python manage.py test
네 맞아요! 프론트랑 백엔드 둘 다에서 항상 권장하더라구요

2020-12-13 15:12 UTC, YeonghyeonKO approved these changes
오.. 이런저런 사소한 차이가 있는데 막 크리티컬하게 차이는 안나네요. 감사합니다!

2020-12-13 15:12 UTC, YeonghyeonKO commented on wafflow/question/models.py
> +    has_accepted = models.BooleanField(default=False)
아 is_hidden 같은 경우는 예시로 든 건데 wafflow에는 필요없겠지만 '나만보기' 같은 기능에서 쓰이는 attribute입니다.
has_accepted도 괜찮을 것 같습니다! 아 아니면 is_answered도 후보가 되겠네요

2020-12-14 07:10 UTC, eldpswp99 commented on .github/workflows/django.yml
> +          DEBUG=TRUE python manage.py test
오 처음 알았네요 ㅎㅎ

2020-12-14 07:13 UTC, eldpswp99 commented on wafflow/question/models.py
> +    has_accepted = models.BooleanField(default=False)
is_answered 는 질문에 답이 달렸는지에 대한 느낌이 강해서 다른 것을 쓰는것이 더 좋아 보입니다. accepted의 통일성도 있구요.

2020-12-14 07:17 UTC, eldpswp99 commented on .github/workflows/django.yml
> +          DEBUG=TRUE python manage.py test
반영해서 커밋 새로 했습니다! 지금 보니 깃헙에서 뉴라인이 없으면 먼가 금지같은 아이콘으로 표시해주네요

2020-12-14 16:58 UTC, YeonghyeonKO commented on wafflow/question/models.py
> +    has_accepted = models.BooleanField(default=False)
넵 그러면 has_accepted로 가는걸로...!

2020-12-15 15:53 UTC, guzus commented on wafflow/answer/models.py
> +
혹시 그냥 INCREMENT 대신에 (INCREMENT, INCREMENT) 이런식으로 튜플을 만드신 이유를 알 수 있을까요?

2020-12-15 15:59 UTC, guzus approved these changes
고칠 점은 없어보입니다! yml 정말 신기하네요. yml 공부하면서 읽었습니다ㅎㅎ 수고하셨습니다!!

2020-12-16 04:11 UTC, eldpswp99 commented on wafflow/answer/models.py
> +
장고 choice를 만드는 문법인데 굳이 alias를 달 필요성을 못느껴서 그냥 똑같이 튜플로 만들었습니다!

2020-12-16 04:50 UTC, merged

2020-12-16 06:04 UTC, guzus commented on wafflow/answer/models.py
> +
앗 그렇군요! 설명 감사합니다!

2020-12-22 10:17 UTC, eldpswp99 commented
> > 아직 모델 단계라서 수정해야 할 부분은 newline 정도밖에 없는 것 같은데
> > 코멘트 남긴 것들에 대해 @guzus @eldpswp99 얘기해봤으면 하네요!
> > 모델 짜느라 정말 수고하셨습니다... 아 혹시 postgresql 사용하면서 mysql과 다른 점 등의 후기를 남겨주실 수 있나요?
> 
> 사실 장고 선에서는 orm을 통해 동작하다보니 postgresql이라고 해서 특별한 것은 딱히 없었고, 있다면 settings 설정과, mysqlclient가 아닌 psycopg2를 사용하는 것 정도? 그 이상으로 크게 다른 점은 없었습니다.
> 
> 다만 postgresql을 콘솔에서 사용할 때 postgres유저로 이동해서 psql을 통해 접속해서 조작할 수 있다는 점, 세미콜론이 없으면 아예 그 문장이 실행이 되지 않고, 무시되면서 아무 메세지도 안나오는 점 등이 다르고, 유저 등록에서도 유저를 추가하면 동명의 우분투 유저가 있어야 한다고 하는등(사실 이 부분은 그냥 따라하긴 했는데 잘 모르겠습니다) 자잘한 문법 차이를 제외하고도 약간 차이가 있더라구요. CI에서도 mysql할 때는 유저에 대한 privilege를 설정해 주어야하는데 postgresql은 따로 설정해 주지 않고, 유저네임을 postgres로 해도 CI가 동작하구요.

이번에 하면서 알게 된건데 "유저네임을 postgres로 해도 CI가 동작하구요."이거는 제가 테스트를 안넣어서 그냥 된 듯 합니다 username제대로 넣어줘야 동작하더라구요