WF-40 [back] Create Admin
wafflestudio18-5/team4-server pull request #40
Opened 2021-01-04 05:52 UTC by guzus

`python manage.py createsuperuser` 를 통해서 admin을 만들 수 있습니다.

2021-01-04 06:42 UTC, eldpswp99 requested changes
현재 admin에서 수정할 때 null=True인 애들은 field=required가 뜹니다
![image](https://user-images.githubusercontent.com/58476210/103507682-0ecec600-4ea3-11eb-9c24-c0ce3d137fde.png)

그리고 vote와 rating은 두개가 연결되어 있는 column들인데, admin페이지에서 rating만을 새로 만들 경우 vote가 바뀌지 않는 문제가 있습니다. rating에 대한 변경을 막아놓던가, vote까지 같이 바뀌게 하는 처리가 필요해 보입니다.

다른 연결된 column이 지금은 vote밖에 떠오르지 않네요 다른 연결된 column이 있다면 그것도 변경이 필요해 보입니다

2021-01-04 06:42 UTC, eldpswp99 commented on wafflow/answer/admin.py
> +    search_fields = ["content"]
question을 통해 찾을 수 있으면 좋을 거 같네요

2021-01-04 07:17 UTC, guzus commented on wafflow/answer/admin.py
> +    search_fields = ["content"]
좋은 피드백 감사합니다!

2021-01-04 15:21 UTC, YeonghyeonKO approved these changes
오 admin 구현은 코드에 비해 가성비가 정말 좋네요..

2021-01-04 15:21 UTC, YeonghyeonKO commented on wafflow/user/serializers.py
> -
근데 저는 changing email에 대해서는 상관없다고 보긴 하는데 기능이 있다면 메일 인증 과정도 필요하지 않을까합니당
이건 추후에 염두에 두는 걸로...

2021-01-04 15:21 UTC, YeonghyeonKO commented on wafflow/answer/admin.py
> +    search_fields = ["content"]
@guzus 명훈님 피드백이 반영된 결과가 다음 사진인가요?
<img width="652" alt="image" src="https://user-images.githubusercontent.com/46114393/103550106-bd96f480-4eeb-11eb-8863-8eae1882f177.png">

2021-01-04 16:30 UTC, guzus commented on wafflow/answer/admin.py
> +    search_fields = ["content"]
@YeonghyeonKO 아뇨! 반영되기 전입니다!

2021-01-04 16:37 UTC, eldpswp99 commented
머지 후에 브랜치 삭제 부탁드려요!

2021-01-04 16:41 UTC, guzus commented on wafflow/answer/admin.py
> +    search_fields = ["content"]
근데 admin에서 validation이 필요한지 고민이 됩니다. 지금은 vote도 100을 더할 수도 있고, 자신의 question에 rating을 할 수 있는 등 admin은 권한이 엄청나게 많습니다. 저는 권한을 그대로 두는 것이 맞다고 생각합니다.(또 모든 column의 required=False로 수정해야 한다고 생각합니다) 그런데 admin이 요상한 user나 question같은 object들을 양산시키면 혼란이 있을 것 같아 그것도 걱정입니다. @eldpswp99 @YeonghyeonKO 어떻게 생각하시는지 궁금합니다!

2021-01-04 16:44 UTC, eldpswp99 commented on wafflow/answer/admin.py
> +    search_fields = ["content"]
근데 어드민에서 그걸 수정할 수 있으면 저희가 db를 만들면서 했던 대전제들이 깨질 수가 있어서 저는 약간 부정적이네요 vote같은 경우도 저희 db에서 항상 전제하고 있는 것은 userquestion의 rating을 모두 합산 = vote라는 것인데 admin에서 그것을 수정할 수 있다는 거 자체가 문제가 된다고 생각해서요

2021-01-04 18:09 UTC, eldpswp99 commented on wafflow/user/serializers.py
> -
네네 저는 사실 지금 메일 인증이 없어서 typo가 생길 가능성때문에 추가했습니다 인증기능 필요해보여요

2021-01-05 04:48 UTC, guzus commented on wafflow/answer/admin.py
> +    search_fields = ["content"]
네 좋은 말씀 감사합니다! 저도 자면서 생각해봤는데 명훈님 말씀대로가 맞는 것 같네요. 좀 더 자유도를 낮추도록 하겠습니다. 영현님도 보시면 의견 부탁드려요!

2021-01-05 09:08 UTC, YeonghyeonKO commented on wafflow/answer/admin.py
> +    search_fields = ["content"]
그렇군요 저도 동의합니다!!

2021-01-05 09:08 UTC, YeonghyeonKO commented on wafflow/user/serializers.py
> -
흠 남는시간동안 해볼까요 ㅋㅋㅋ 2시간컷 가능한데

2021-01-06 04:28 UTC, eldpswp99 reviewed
foriegn key로 연결되어 있는 모델들은 delete?로 삭제가 가능한듯 한데, 이 부분은 admin에서 삭제는 가능하도록 의도하신 건가요? 이 기능은 있어도 될 듯하긴 합니다 그 외에는 문제 없어보이네요 고생하셨습니다!

2021-01-06 04:28 UTC, eldpswp99 commented on wafflow/user/serializers.py
> -
ㅋㅋㅋㅋ pr만 열어두고 완성 후에 하는것도 괜찮아 보여요 프론트분들이 얼마나 완성이 되있는지 지금 잘 모르겠어서 감이 안오네요

2021-01-06 04:29 UTC, eldpswp99 approved these changes

2021-01-06 04:45 UTC, guzus commented
> foriegn key로 연결되어 있는 모델들은 delete?로 삭제가 가능한듯 한데, 이 부분은 admin에서 삭제는 가능하도록 의도하신 건가요? 이 기능은 있어도 될 듯하긴 합니다 그 외에는 문제 없어보이네요 고생하셨습니다!

네네 하다보니까 그 기능이 있어서 넣었습니다

2021-01-06 08:44 UTC, YeonghyeonKO approved these changes

2021-01-06 08:54 UTC, merged