WF-11 [back] build bookmark app
wafflestudio18-5/team4-server pull request #8
Opened 2020-12-23 08:30 UTC by eldpswp99

build bookmark app
build bookmark test

bookmark delete를 하는 과정에서 get_or_create를 사용할지 말지에 대한 고민이 있었지만,
(아무런 UserQuestion이 없을 때 잘못된 요청이 들어와도 새로운 UserQuestion instance를 만들기 떄문에)

delete에 잘못된 요청이 들어올 이유가 많지 않은 점, response에서 serializer을 이용하기 위해 get_or_create를 사용하였습니다

2020-12-25 17:33 UTC, guzus approved these changes

2020-12-25 17:33 UTC, guzus commented on wafflow/bookmark/views.py
> +
신기하네요..!

2020-12-25 18:07 UTC, eldpswp99 commented on wafflow/bookmark/views.py
> +
이 PR은 아직 작업중이라..작업이 끝나면 앞의 WIP를 떼도록하겠습니다

2020-12-26 11:00 UTC, guzus requested changes

2020-12-26 11:00 UTC, guzus commented on wafflow/bookmark/views.py
> +        page = int(request.query_params.get("page"))
만약에 sorted_by 나 page가 none로 들어올 경우를 생각해야 될 것 같습니다!

2020-12-26 11:02 UTC, guzus commented on wafflow/bookmark/views.py
> +        page = int(request.query_params.get("page"))
sorted_by는 문제가 되지 않을거 같네요!

2020-12-26 14:36 UTC, eldpswp99 commented on wafflow/bookmark/views.py
> +        page = int(request.query_params.get("page"))
수정하였습니다!

2020-12-26 15:51 UTC, YeonghyeonKO approved these changes

2020-12-26 15:51 UTC, YeonghyeonKO commented on wafflow/bookmark/views.py
> +        )
make 때와 달리 get_or_create 보다는 get으로 불러와서 없는 경우 따로 빠지게 하는게 낫지 않을까요?

2020-12-26 15:51 UTC, YeonghyeonKO commented on wafflow/bookmark/views.py
> +        page = int(page)
get("page") 썼을 때 None이 int()에 들어갈 수도 있지 않을까요?

2020-12-26 15:51 UTC, YeonghyeonKO commented on wafflow/bookmark/views.py
> +                map(lambda user_question: user_question.question, user_questions)
기존과 달리 lambda를 사용하셨는데 차이점이 있을까요?

2020-12-26 16:13 UTC, eldpswp99 commented on wafflow/bookmark/views.py
> +        )
그렇겠네요 수정하겠습니다

2020-12-26 16:13 UTC, eldpswp99 commented on wafflow/bookmark/views.py
> +        page = int(page)
위에서 page is None이 있어서 괜찮을거 같습니다

2020-12-26 16:13 UTC, eldpswp99 commented on wafflow/bookmark/views.py
> +                map(lambda user_question: user_question.question, user_questions)
기존의 것은 question__in = QuerySet인데, 이거는 sorting이 되지 않게 됩니다. question__in = [4,3,2,1] 이렇게 되어있어도 그냥 [4,3,2,1]에 속하는 question만을 불러오고 순서가 일정하게 유지되지 않는것을 확인하여 sorting이 되도록 수정하였습니다

2020-12-26 16:15 UTC, YeonghyeonKO commented on wafflow/bookmark/views.py
> +        )
@eldpswp99 
`delete에 잘못된 요청이 들어올 이유가 많지 않은 점, response에서 serializer을 이용하기 위해 get_or_create를 사용하였습니다`
아이고 제가 이걸 안보고 남긴 코멘트인데 최근에 추가하신 문장은 아니죠?

2020-12-26 16:16 UTC, YeonghyeonKO commented on wafflow/bookmark/views.py
> +        page = int(page)
아 뒤에 붙어있었군요 ㅎㅎ

2020-12-26 16:17 UTC, YeonghyeonKO commented on wafflow/bookmark/views.py
> +                map(lambda user_question: user_question.question, user_questions)
아 sort 반영하고자 쓰신거군요

2020-12-26 16:22 UTC, eldpswp99 commented on wafflow/bookmark/views.py
> +        )
그렇긴한데 다시 생각해보면 나누는게 나을거같아서요

2020-12-26 16:33 UTC, YeonghyeonKO commented on wafflow/bookmark/views.py
> +        )
넵넵 의도 잘 이해했습니다! 그런데 이렇게 Delete API임에도 serializer를 줘야하는 경우는 다들 어떻게 하는지 궁금하긴 하네요

2020-12-26 18:04 UTC, merged